import {GradumIcon, h1, GradumEventManager, gradum} from "../../../build/gradum-kit.esm";
import {setupIconTests} from "./cases/icon/icon";
import {setupRichElementTests} from "./cases/richElement/richElement";
import {setupInputTests} from "./cases/input/input";
import {setupSelectTests} from "./cases/select/select";
import {setupDrawerTests} from "./cases/drawer/drawer";
import {setupPopupTests} from "./cases/popup/popup";
import {setupDropdownTests} from "./cases/dropdown/dropdown";
import {setupSelectWheelTests} from "./cases/selectWheel/selectWheel";
import {setupContentSwitchTests} from "./cases/contentSwitch/contentSwitch";

gradum(GradumIcon.defaultProperties).applyDefaults({directory: "assets", defaultClasses: "icon"});
GradumEventManager.instance.preventDefaultWheel = false;

h1({text: "GradumIcon", parent: document.body});
setupIconTests();
h1({text: "GradumRichElement", parent: document.body});
setupRichElementTests();
h1({text: "GradumInput", parent: document.body});
setupInputTests();
h1({text: "GradumSelect", parent: document.body});
setupSelectTests();
h1({text: "GradumDrawer", parent: document.body});
setupDrawerTests();
h1({text: "GradumPopup", parent: document.body});
setupPopupTests();
h1({text: "GradumDropdown", parent: document.body});
setupDropdownTests();
h1({text: "GradumSelectWheel", parent: document.body});
setupSelectWheelTests();
h1({text: "GradumContentSwitch", parent: document.body});
setupContentSwitchTests();